version: '3.8'

services:
  mongoService:
    env_file:
      - .env
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongoData:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    restart: always
    
volumes:
  mongoData: